// Command demosvg renders a captured gpu-reaper log as the README's terminal
// image, so the picture is generated from a real run rather than typed in.
//
//	make demo-record   # captures docs/demo.log, then runs this
//
// What it changes, all stated in the image caption:
//   - keeps the "starting" and "observe mode" lines, every "cycle complete"
//     line, the first finding for each (job, verdict) pair, and every
//     "would drain" line; drops the rest (repeated findings, the Slack and
//     metrics-listener lines);
//   - shortens time=... to HH:MM:SS;
//   - wraps long lines. No text inside a kept line is removed or edited.
//
// The full, unfiltered capture is committed next to the image as docs/demo.log.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"html"
	"io"
	"os"
	"regexp"
	"strings"
)

const (
	width    = 1000
	lineH    = 16
	wrapAt   = 112
	indent   = "        "
	topPad   = 64
	fontSize = 10.5
)

var (
	timeRe    = regexp.MustCompile(`^time=\S*T(\d\d:\d\d:\d\d)\S* `)
	findingRe = regexp.MustCompile(`msg=finding verdict=([a-z]+) .*job_id=(\S+)`)
)

func keep(line string, seen map[string]bool) bool {
	switch {
	case strings.Contains(line, "msg=starting"),
		strings.Contains(line, `msg="observe mode`),
		strings.Contains(line, `msg="cycle complete"`),
		strings.Contains(line, `msg="would drain"`):
		return true
	}
	if m := findingRe.FindStringSubmatch(line); m != nil {
		key := m[2] + "/" + m[1]
		if !seen[key] {
			seen[key] = true
			return true
		}
	}
	return false
}

func wrap(s string) []string {
	var out []string
	for len(s) > wrapAt {
		cut := strings.LastIndex(s[:wrapAt], " ")
		if cut <= len(indent) {
			cut = wrapAt
		}
		out = append(out, s[:cut])
		s = indent + strings.TrimLeft(s[cut:], " ")
	}
	return append(out, s)
}

func class(line string) string {
	switch {
	case strings.Contains(line, "level=WARN"):
		return "warn"
	case strings.Contains(line, "level=ERROR"):
		return "err"
	case strings.Contains(line, "msg=finding"):
		return "find"
	case strings.Contains(line, `msg="would drain"`):
		return "drain"
	}
	return "txt"
}

func main() {
	cmd := flag.String("cmd", "gpu-reaper --config demo/config.yaml --cycles 9", "command shown at the prompt")
	flag.Parse()

	var rows [][2]string // class, text
	seen := map[string]bool{}
	sc := bufio.NewScanner(os.Stdin)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := sc.Text()
		if !keep(line, seen) {
			continue
		}
		c := class(line)
		line = timeRe.ReplaceAllString(line, "$1 ")
		for i, w := range wrap(line) {
			if i > 0 && c == "txt" {
				c = "dim"
			}
			rows = append(rows, [2]string{c, w})
		}
	}
	if err := sc.Err(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	write(os.Stdout, *cmd, rows)
}

func write(w io.Writer, cmd string, rows [][2]string) {
	caption := wrap("Generated by hack/demosvg from a real run captured in docs/demo.log (make demo-record). " +
		"Omitted: repeated findings, and the Slack and metrics-listener lines. Timestamps shortened to HH:MM:SS; " +
		"long lines wrapped; nothing else edited. Telemetry is the simulator and squeue is a fake: " +
		"no GPUs, no Slurm controller, no cluster.")
	for i := range caption {
		caption[i] = strings.TrimLeft(caption[i], " ")
	}
	h := topPad + lineH*len(rows) + 28 + lineH*len(caption) + 20
	fmt.Fprintf(w, `<svg xmlns="http://www.w3.org/2000/svg" width="%d" height="%d" viewBox="0 0 %d %d" role="img" aria-label="Terminal capture of a bounded gpu-reaper demo run in observe mode: no finding until the window is covered, then alerts, then one dry-run drain per node; nothing cancelled.">`+"\n", width, h, width, h)
	fmt.Fprintf(w, `<style>
text { font-family: 'JetBrains Mono','SF Mono',Menlo,Consolas,monospace; font-size: %.1fpx; white-space: pre; }
.txt { fill: #cdd6df; } .dim { fill: #8b96a3; } .warn { fill: #f5b544; } .err { fill: #f85149; }
.find { fill: #f5b544; } .drain { fill: #58a6ff; } .prompt { fill: #3fb950; } .cmd { fill: #e9eff5; font-weight: 600; }
.cap { fill: #7d8894; }
</style>
`, fontSize)
	fmt.Fprintf(w, `<rect width="%d" height="%d" rx="10" fill="#141a23"/>`+"\n", width, h)
	fmt.Fprint(w, `<circle cx="24" cy="22" r="5" fill="#ff5f56"/><circle cx="42" cy="22" r="5" fill="#ffbd2e"/><circle cx="60" cy="22" r="5" fill="#27c93f"/>`+"\n")
	fmt.Fprintf(w, `<line x1="0" y1="40" x2="%d" y2="40" stroke="#243040"/>`+"\n", width)
	fmt.Fprintf(w, `<text x="20" y="%d"><tspan class="prompt">$ </tspan><tspan class="cmd">%s</tspan></text>`+"\n", topPad-8, html.EscapeString(cmd))
	y := topPad + lineH
	for _, r := range rows {
		fmt.Fprintf(w, `<text class="%s" x="20" y="%d">%s</text>`+"\n", r[0], y, html.EscapeString(r[1]))
		y += lineH
	}
	y += 12
	fmt.Fprintf(w, `<line x1="20" y1="%d" x2="%d" y2="%d" stroke="#1e2836"/>`+"\n", y-lineH+4, width-20, y-lineH+4)
	for _, c := range caption {
		fmt.Fprintf(w, `<text class="cap" x="20" y="%d">%s</text>`+"\n", y, html.EscapeString(c))
		y += lineH
	}
	fmt.Fprintln(w, "</svg>")
}
